spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@db202108051346_high?TNS_ADMIN=C:/somin/Spring/resource/wallet
    username: admin
    password: Qkrthals0283!
